### ISSUE TITLE
CampusGuide-Mobile:  Add Map 

### ISSUE THREAD

**Issue by vickystickz** [vickystickz/CampusGuide-mobile#3]
**Requirement:** 
- [x] Setup env variables for mapbox token
- [x] Render Map 

**Vector tiles:**
Street: "mapbox://styles/mapbox/streets-v11",
Satellite Imagery: "mapbox://styles/mapbox/satellite-v9",

**Comment by jeafreezy** [comment]
Could you provide the token @vickystickz .

Also, since there's already an implementation of basemap switching on the web version, help with the vector tiles config/styles id/xyz tiles used here so it can be consistent.

**Comment by vickystickz** [comment]
> Could you provide the token @vickystickz .
> 
> Also, since there's already an implementation of basemap switching on the web version, help with the vector tiles config/styles id/xyz tiles used here so it can be consistent.

I will send the token privately to you
I have added the map style URL to the requirement description above
